language: python
dist: trusty

python:
  - "2.7"

services:
  - docker

cache:
  directories:
  - ~/docker

install:
  - sudo rm /etc/apt/sources.list.d/docker.list
  - if [[ -e ~/docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi
  - docker pull frappe/erpnext:ubuntu_16.04_develop
  - mkdir -p ~/docker; docker save frappe/erpnext:ubuntu_16.04_develop > ~/docker/image.tar

before_script:
  - docker run -d -p 127.0.0.1:80:4567 -it --name erpnext-travis frappe/erpnext:ubuntu_16.04_develop
  - sleep 10
  # - docker exec -i erpnext-travis bash -c "wget http://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip"
  # - docker exec -i erpnext-travis bash -c "unzip chromedriver_linux64.zip"
  # - docker exec -i erpnext-travis bash -c "apt-get install libnss3"
  # - docker exec -i erpnext-travis bash -c "apt-get install google-chrome-stable xvfb"
  # - docker exec -i erpnext-travis bash -c "cp chromedriver /usr/local/bin/."
  # - docker exec -i erpnext-travis bash -c "chmod +x /usr/local/bin/chromedriver"
  # - docker exec -i erpnext-travis bash -c "export DISPLAY=:99.0"
  # - docker exec -i erpnext-travis bash -c "service mysql restart"

  # Update frappe
  - free
  - docker exec -itu frappe erpnext-travis zsh -c "cd /home/frappe/frappe-bench/apps/frappe && git pull"
  # - PR_BRANCH_HEAD=$(docker exec -itu frappe erpnext-travis zsh -c "cd /home/frappe/frappe-bench/apps/erpnext && git rev-parse HEAD")
  # - docker exec -itu frappe erpnext-travis bash -c "cd ~/frappe-bench/apps/erpnext && git remote add test ~/erpnext/ && git fetch --unshallow test && git checkout -b test -t test/$TRAVIS_BRANCH"
  # - CURRENT_BRANCH_HEAD=$(docker exec -itu frappe erpnext-travis bash -c "cd ~/frappe-bench/apps/erpnext && git rev-parse HEAD")
  # - diff <( echo \"$PR_BRANCH_HEAD\" ) <( echo \"$CURRENT_BRANCH_HEAD\" )
  # - docker exec -itu frappe erpnext-travis bash -c "cd ~/frappe-bench/apps/frappe && git config --global user.email 'you@example.com' && git config --global user.name 'Your Name' && git add . && git stash && git pull --rebase upstream develop"
  - docker exec -itu frappe erpnext-travis zsh -c "cd /home/frappe/frappe-bench && bench setup requirements && bench build"
  - docker exec -itu frappe erpnext-travis zsh -c "cd /home/frappe/frappe-bench && bench reinstall --yes && bench migrate"
  - docker exec -itu frappe erpnext-travis zsh -c "cd /home/frappe/frappe-bench && bench scheduler disable"
  # - docker exec -itu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench start &"
  - docker exec -idu frappe erpnext-travis zsh -c "cd /home/frappe/frappe-bench && bench start"
  # - docker exec -itu frappe erpnext-travis bash -c "cd ~/frappe-bench && sleep 10"
  
  - sleep 10 
  # - docker exec -it erpnext-travis bash -c "service xvfb restart"
  - set -e

jobs:
  include:
    - stage: test
      script:
        - set -e
        # - bench run-tests
        - docker exec -iu frappe erpnext-travis bash -c "cd ~/frappe-bench && bench run-tests"
      env: Server Side Test
